# Generated by Django 2.1.3 on 2018-12-11 00:06

from django.db import migrations, models
import fuente.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Indíquenos su nombre completo.', max_length=50, verbose_name='Nombres y apellidos')),
                ('cedula', models.CharField(help_text='Indíquenos su número de cédula.', max_length=20, verbose_name='Cédula')),
                ('telefono', models.CharField(help_text='Indíquenos su número de teléfono movil.', max_length=20, verbose_name='Teléfono celular')),
                ('email', models.EmailField(blank=True, help_text='Indíquenos su correo electrónico.', max_length=254, verbose_name='Correo electrónico')),
                ('nota', models.TextField(blank=True, verbose_name='Comentario adicional')),
                ('consentimiento', models.CharField(help_text='Declaro haber leído la política de privacidad, y estar de acuerdo con ella.', max_length=50, verbose_name='Estoy de acuerdo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
            bases=(models.Model, fuente.base.Texto),
        ),
    ]
