# Generated by Django 2.1.3 on 2018-12-11 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AddField(
            model_name='prestamo',
            name='cuenta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta', verbose_name='Cuenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='cuotas',
            field=models.IntegerField(default=1, verbose_name='Cuotas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(auto_now=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto del préstamo.', max_digits=12, verbose_name='Monto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='periodo',
            field=models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=10, verbose_name='Periodo de pagos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='Tasa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='user',
            field=models.ForeignKey(default=None, editable=False, help_text='Usuario que registró la solicitud (opcional)', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
