# Generated by Django 2.1.3 on 2018-12-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_auto_20181214_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='ref1_parentesco',
            field=models.CharField(blank=True, max_length=20, verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ref2_parentesco',
            field=models.CharField(blank=True, max_length=20, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='carta_de_trabajo_file',
            field=models.FileField(blank=True, help_text='Suba la carta de trabajo escaneada.', upload_to='prestamos/solicitud/%Y/%m/', verbose_name='Carta de trabajo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cedula_file',
            field=models.FileField(blank=True, help_text='Suba la copia de su cédula.', upload_to='prestamos/solicitud/%Y/%m/', verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='consentimiento',
            field=models.BooleanField(help_text='Declaro haber leído la política de privacidad, y estar de acuerdo con ella.', verbose_name='Estoy de acuerdo'),
        ),
    ]
