# Generated by Django 2.1.3 on 2018-12-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_auto_20181215_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='trabajo_inicio',
            field=models.DateField(blank=True, help_text='Fecha en que empezó a formar parte de la empresa como empleado.', null=True, verbose_name='Fecha en que ingresó'),
        ),
    ]
