# Generated by Django 2.1.3 on 2018-12-15 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0007_auto_20181215_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='cuenta',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
        ),
    ]
