# Generated by Django 2.1.3 on 2018-12-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente'),
        ('contabilidad', '0002_auto_20181214_1916'),
        ('prestamos', '0008_auto_20181215_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cliente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='cuenta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta', verbose_name='Cuenta'),
        ),
    ]
