# Generated by Django 2.1.3 on 2018-12-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_auto_20181215_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='cliente',
        ),
    ]
