# Generated by Django 2.1.3 on 2018-12-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0010_remove_prestamo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prestamos.Prestamo', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
