# Generated by Django 2.1.3 on 2018-12-16 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0011_prestamo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='Cliente'),
        ),
    ]
