# Generated by Django 2.1.3 on 2018-12-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0012_auto_20181216_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cuotas_tipo',
            field=models.CharField(choices=[('FIJA', 'Cuota fija'), ('VARIABLE', 'Cuota variable')], default='FIJA', max_length=10, verbose_name='Tipo de cuotas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
