# Generated by Django 2.1.3 on 2018-12-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('tags', models.CharField(blank=True, max_length=100, verbose_name='Etiquetas')),
                ('active', models.BooleanField(default=True, verbose_name='¿Disponible?')),
                ('img_width', models.PositiveIntegerField(blank=True, editable=False)),
                ('img_height', models.PositiveIntegerField(blank=True, editable=False)),
                ('img', models.ImageField(height_field='img_height', upload_to='tienda/post/%Y/%m/', verbose_name='Imágen', width_field='img_width')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
