# Generated by Django 2.1.3 on 2018-12-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20181207_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_height',
            field=models.PositiveIntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_width',
            field=models.PositiveIntegerField(blank=True, editable=False),
        ),
    ]
