# Generated by Django 2.1.3 on 2018-12-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pubdate',
            new_name='pub_date',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=100, verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
