# Generated by Django 2.1.3 on 2018-12-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('content', models.TextField(help_text='Nota: se acepta código HTML', verbose_name='Contenido')),
                ('tags', models.CharField(blank=True, max_length=100, verbose_name='Etiquetas')),
                ('image', models.ImageField(help_text='Imagen que se mostrará junto al título de la publicación', upload_to='blog/post/%Y/%m/', verbose_name='Imagen')),
                ('slug', models.SlugField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
