# Generated by Django 2.1.3 on 2018-12-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen que se mostrará junto al título de la publicación', upload_to='blog/post/%Y/%m/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
