# Generated by Django 2.1.3 on 2018-12-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181208_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visitas',
            field=models.IntegerField(default=0, editable=False, help_text='Cantidad de visitas a esta entrada', verbose_name='Visitas'),
        ),
    ]
