# Generated by Django 2.1.3 on 2018-12-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181208_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la búsqueda', verbose_name='Descripción'),
        ),
    ]
