# Generated by Django 2.1.3 on 2018-12-16 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_auto_20181216_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='Usuario que creó esto.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
