# Generated by Django 2.1.3 on 2018-12-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('value', models.TextField(verbose_name='Valor')),
                ('value_type', models.CharField(choices=[('STR', 'Texto'), ('INT', 'Número entero.'), ('FLOAT', 'Número de coma flotante.'), ('DECIMAL', 'Número decimal'), ('TUPLE', 'Tupla'), ('LIST', 'Lista'), ('DICT', 'Diccionario'), ('BOOL', 'Falso/Verdadero')], default='STR', max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
