# Generated by Django 2.1.3 on 2018-11-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('viewname', models.CharField(max_length=20, verbose_name='View')),
                ('group', models.CharField(max_length=50, verbose_name='Grupo')),
                ('cssclass', models.CharField(default='link', max_length=50, verbose_name='CSS class')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
            },
        ),
        migrations.RenameModel(
            old_name='Configurations',
            new_name='Configuration',
        ),
    ]
