# Generated by Django 2.1.3 on 2018-11-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20181121_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='group',
            field=models.CharField(choices=[('NAV', 'Navegación'), ('CREDITS', 'Créditos')], max_length=50, verbose_name='Grupo'),
        ),
    ]
