# Generated by Django 2.1.3 on 2018-11-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20181121_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='link',
            name='viewname',
            field=models.CharField(blank=True, max_length=20, verbose_name='View'),
        ),
    ]
