# Generated by Django 2.1.3 on 2018-12-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20181121_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='group',
            field=models.CharField(choices=[('NAV', 'Barra de navegación'), ('CREDITS', 'Créditos'), ('prestamos', 'Préstamos')], help_text='Grupo de enlaces al cual pertenece.', max_length=50, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='link',
            name='viewname',
            field=models.CharField(blank=True, help_text='Nombre de la vista (View) a la cual apuntará la url.', max_length=100, verbose_name='View'),
        ),
    ]
