# Generated by Django 2.1.3 on 2018-12-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20181201_0103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
